/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline': '#717786',
        'surface-container': '#f0edef',
        'on-primary-container': '#fefcff',
        'on-primary-fixed-variant': '#004493',
        'surface-container-high': '#eae7ea',
        'primary-fixed': '#d8e2ff',
        'on-error-container': '#93000a',
        'on-surface-variant': '#414755',
        'surface-dim': '#dcd9dc',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#adc6ff',
        'on-secondary-fixed-variant': '#3631b4',
        'secondary-fixed': '#e2dfff',
        'surface-container-low': '#f6f3f5',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#c2c1ff',
        'inverse-on-surface': '#f3f0f2',
        'surface-bright': '#fcf8fb',
        'on-tertiary-fixed-variant': '#7c2e00',
        'on-primary-fixed': '#001a41',
        'tertiary-fixed-dim': '#ffb595',
        'error-container': '#ffdad6',
        'outline-variant': '#c1c6d7',
        'surface': '#fcf8fb',
        'on-background': '#1b1b1d',
        'primary-fixed-dim': '#adc6ff',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#0c006a',
        'primary-container': '#0070eb',
        'tertiary-container': '#c64f00',
        'surface-tint': '#005bc1',
        'tertiary-fixed': '#ffdbcc',
        'error': '#ba1a1a',
        'background': '#fcf8fb',
        'secondary': '#4c4aca',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e4e2e4',
        'surface-container-highest': '#e4e2e4',
        'primary': '#0058bc',
        'on-tertiary-fixed': '#351000',
        'on-error': '#ffffff',
        'on-secondary-container': '#fffbff',
        'tertiary': '#9e3d00',
        'on-surface': '#1b1b1d',
        'inverse-surface': '#303032',
        'on-tertiary-container': '#fffbff',
        'secondary-container': '#6664e4',
        'nova': '#22d3ee',
        'nova-soft': '#67e8f9',
        'nova-deep': '#0891b2',
      },
      transitionTimingFunction: {
        focus: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        nova: ['Manrope', 'sans-serif'],
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top, 0px)',
        'safe-bottom': 'env(safe-area-inset-bottom, 0px)',
        'safe-left': 'env(safe-area-inset-left, 0px)',
        'safe-right': 'env(safe-area-inset-right, 0px)',
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        '.pt-safe':  { paddingTop:    'env(safe-area-inset-top, 0px)' },
        '.pb-safe':  { paddingBottom: 'env(safe-area-inset-bottom, 0px)' },
        '.pl-safe':  { paddingLeft:   'env(safe-area-inset-left, 0px)' },
        '.pr-safe':  { paddingRight:  'env(safe-area-inset-right, 0px)' },
        '.mt-safe':  { marginTop:     'env(safe-area-inset-top, 0px)' },
        '.mb-safe':  { marginBottom:  'env(safe-area-inset-bottom, 0px)' },
        '.top-safe': { top:           'env(safe-area-inset-top, 0px)' },
        '.bottom-safe': { bottom:     'env(safe-area-inset-bottom, 0px)' },
        '.h-safe-bottom': { height:   'env(safe-area-inset-bottom, 0px)' },
      })
    },
  ],
}
